insert into customers (name, email)
values
  ('emma watson', 'emma.watson@gmail.com'),
  ('michael scott', 'michael.scott@gmail.com'),
  ('sarah connor', 'sarah.connor@gmail.com'),
  ('james smith', 'james.smith@gmail.com'),
  ('olivia davis', 'olivia.davis@gmail.com'),
  ('liam thompson', 'liam.thompson@gmail.com'),
  ('ava johnson', 'ava.johnson@gmail.com'),
  ('noah williams', 'noah.williams@gmail.com'),
  ('mia brown', 'mia.brown@gmail.com'),
  ('ethan jones', 'ethan.jones@gmail.com'),
  ('amelia taylor', 'amelia.taylor@gmail.com'),
  ('lucas anderson', 'lucas.anderson@gmail.com'),
  ('grace martin', 'grace.martin@gmail.com'),
  ('benjamin moore', 'benjamin.moore@gmail.com'),
  ('ella thomas', 'ella.thomas@gmail.com'),
  ('jack white', 'jack.white@gmail.com'),
  ('sofia harris', 'sofia.harris@gmail.com'),
  ('daniel clark', 'daniel.clark@gmail.com'),
  ('chloe lewis', 'chloe.lewis@gmail.com'),
  ('henry walker', 'henry.walker@gmail.com'),
  ('lily hall', 'lily.hall@gmail.com'),
  ('sebastian allen', 'sebastian.allen@gmail.com'),
  ('nora young', 'nora.young@gmail.com'),
  ('david king', 'david.king@gmail.com'),
  ('zoe scott', 'zoe.scott@gmail.com'),
  ('alexander green', 'alexander.green@gmail.com'),
  ('victoria baker', 'victoria.baker@gmail.com'),
  ('logan nelson', 'logan.nelson@gmail.com'),
  ('natalie turner', 'natalie.turner@gmail.com'),
  ('owen cooper', 'owen.cooper@gmail.com');

